set relativenumber
set number
set ruler
set hlsearch
set ignorecase
set incsearch
syntax on
set smartcase
set fileencoding=utfa8
set laststatus=2
set statusline+=%F
"set title
colors Tomorrow-Night-Eighties
